name: xgb-fdem
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - pip:
      - numpy==2.4.6
      - scipy==1.18.0
      - pandas==3.0.3
      - scikit-learn==1.9.0
      - xgboost==3.3.0
      - matplotlib==3.11.1
      - seaborn==0.13.2
      - joblib==1.5.3
      - empymod==2.6.0
      - pygimli==1.6.0
      - jupyterlab
